name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake=3.16.*

      - name: Create build directory
        run: mkdir -p build

      - name: Run CMake
        run: cmake -DENABLE_UT=TRUE -S . -B build

      - name: Build project
        run: cmake --build build

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Run unit tests
        run: |
         ./src/test/LRU_Test
        working-directory: build

  